version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    volumes:
      - /data/mysql
    ports:
      - "3306:3306"

  application:
    image: application:1
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - /data/app
    ports:
      - "5005:5005"
      - "8084:8084"