#Spring DATA SOURCE Configurations
spring:
  datasource:
    url: "jdbc:postgresql://rdbms:5432/test?useSSL=false"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog.sql

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always