version: '3'
services:
  rdbms:
    build:
      dockerfile: rdbms/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - /data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
      interval: 10s
      retries: 1

  application:
    build:
      context: ../..
      dockerfile: ./tools/docker/application/Dockerfile
    depends_on:
      rdbms:
        condition: service_healthy
    volumes:
      - /data/app
    ports:
      - "5005:5005"
      - "8084:8084"
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:8084/actuator/health" ]
      timeout: 5s
      interval: 5s
      retries: 3