version: '3'
services:
  rdbms:
    build:
      dockerfile: rdbms/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    volumes:
      - /data/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  application:
    image: application:1
    build:
      context: ../..
      dockerfile: ./tools/docker/application/Dockerfile
    depends_on:
      rdbms:
        condition: service_healthy
    volumes:
      - /data/app
    ports:
      - "8084:8084"